var texts = [
"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed feugiat arcu eu convallis rutrum. Ut placerat tempor ante a feugiat. Integer pretium nisi ac tristique egestas. Quisque accumsan sed justo sit amet gravida. Donec elementum molestie eros, id iaculis magna volutpat a. Pellentesque sit amet quam nibh. Maecenas sollicitudin nunc ac porta volutpat. Proin et nulla id ante rutrum laoreet non in eros.\n" + 
"Sed sed odio interdum nibh iaculis imperdiet. Sed at aliquet lorem. Suspendisse tincidunt tempus felis, nec porttitor libero vulputate eu. Nam porta eros vitae sodales ultrices. Cras condimentum ornare vehicula. Nullam in semper massa. Mauris molestie ante eros, nec sagittis ipsum ornare nec.\n" +
"Nam gravida facilisis magna, at pharetra eros ornare sed. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Vivamus pharetra pulvinar ligula, ac mollis nisl imperdiet sed. Proin pharetra diam ac semper bibendum. Quisque eget efficitur ante. Aenean dapibus nulla eget risus faucibus, non dapibus nisi vestibulum. Pellentesque consequat, quam in pharetra aliquet, orci eros sagittis ligula, vitae lacinia ex enim at magna.\n" +
"Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Etiam in felis nisi. Nam tempor, metus in pellentesque malesuada, quam ex egestas massa, eu suscipit elit magna ut orci. Quisque accumsan neque diam, sed facilisis orci condimentum hendrerit. Mauris elementum tortor ipsum, non malesuada mi lobortis viverra. Mauris vel arcu luctus, tristique enim sit amet, eleifend diam. Interdum et malesuada fames ac ante ipsum primis in faucibus.\n" +
"Curabitur ultrices posuere metus et finibus. Etiam ornare tortor nec libero finibus, non tristique diam bibendum. Sed cursus magna ut tellus consequat, ac eleifend elit feugiat. Duis vehicula purus in tellus vestibulum, eget suscipit nibh convallis. Pellentesque orci elit, ultrices in pellentesque a, convallis quis enim. Aenean at porta lacus. Donec sollicitudin viverra lacus et ultrices. Suspendisse malesuada ligula eu leo dictum, non viverra metus varius. Mauris sit amet placerat neque. Cras consequat tortor et quam lacinia, vel gravida dui consectetur. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Fusce eu nisi sapien.\n",

"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed feugiat arcu eu convallis rutrum. Ut placerat tempor ante a feugiat. Integer pretium nisi ac tristique egestas. Quisque accumsan sed justo sit amet gravida. Donec elementum molestie eros, id iaculis magna volutpat a. Pellentesque sit amet quam nibh. Maecenas sollicitudin nunc ac porta volutpat. Proin et nulla id ante rutrum laoreet non in eros.\n" + 
"Sed sed odio interdum nibh iaculis imperdiet. Sed at aliquet lorem. Suspendisse tincidunt tempus felis, nec porttitor libero vulputate eu. Nam porta eros vitae sodales ultrices. Cras condimentum ornare vehicula. Nullam in semper massa. Mauris molestie ante eros, nec sagittis ipsum ornare nec.\n" +
"Nam gravida facilisis magna, at pharetra eros ornare sed. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Vivamus pharetra pulvinar ligula, ac mollis nisl imperdiet sed. Proin pharetra diam ac semper bibendum. Quisque eget efficitur ante. Aenean dapibus nulla eget risus faucibus, non dapibus nisi vestibulum. Pellentesque consequat, quam in pharetra aliquet, orci eros sagittis ligula, vitae lacinia ex enim at magna.\n" +
"Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Etiam in felis nisi. Nam tempor, metus in pellentesque malesuada, quam ex egestas massa, eu suscipit elit magna ut orci. Quisque accumsan neque diam, sed facilisis orci condimentum hendrerit. Mauris elementum tortor ipsum, non malesuada mi lobortis viverra. Mauris vel arcu luctus, tristique enim sit amet, eleifend diam. Interdum et malesuada fames ac ante ipsum primis in faucibus.\n" +
"Curabitur ultrices posuere metus et finibus. Etiam ornare tortor nec libero finibus, non tristique diam bibendum. Sed cursus magna ut tellus consequat, ac eleifend elit feugiat. Duis vehicula purus in tellus vestibulum, eget suscipit nibh convallis. Pellentesque orci elit, ultrices in pellentesque a, convallis quis enim. Aenean at porta lacus. Donec sollicitudin viverra lacus et ultrices. Suspendisse malesuada ligula eu leo dictum, non viverra metus varius. Mauris sit amet placerat neque. Cras consequat tortor et quam lacinia, vel gravida dui consectetur. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Fusce eu nisi sapien.\n",

"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed feugiat arcu eu convallis rutrum. Ut placerat tempor ante a feugiat. Integer pretium nisi ac tristique egestas. Quisque accumsan sed justo sit amet gravida. Donec elementum molestie eros, id iaculis magna volutpat a. Pellentesque sit amet quam nibh. Maecenas sollicitudin nunc ac porta volutpat. Proin et nulla id ante rutrum laoreet non in eros.\n" + 
"Sed sed odio interdum nibh iaculis imperdiet. Sed at aliquet lorem. Suspendisse tincidunt tempus felis, nec porttitor libero vulputate eu. Nam porta eros vitae sodales ultrices. Cras condimentum ornare vehicula. Nullam in semper massa. Mauris molestie ante eros, nec sagittis ipsum ornare nec.\n" +
"Nam gravida facilisis magna, at pharetra eros ornare sed. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Vivamus pharetra pulvinar ligula, ac mollis nisl imperdiet sed. Proin pharetra diam ac semper bibendum. Quisque eget efficitur ante. Aenean dapibus nulla eget risus faucibus, non dapibus nisi vestibulum. Pellentesque consequat, quam in pharetra aliquet, orci eros sagittis ligula, vitae lacinia ex enim at magna.\n" +
"Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Etiam in felis nisi. Nam tempor, metus in pellentesque malesuada, quam ex egestas massa, eu suscipit elit magna ut orci. Quisque accumsan neque diam, sed facilisis orci condimentum hendrerit. Mauris elementum tortor ipsum, non malesuada mi lobortis viverra. Mauris vel arcu luctus, tristique enim sit amet, eleifend diam. Interdum et malesuada fames ac ante ipsum primis in faucibus.\n" +
"Curabitur ultrices posuere metus et finibus. Etiam ornare tortor nec libero finibus, non tristique diam bibendum. Sed cursus magna ut tellus consequat, ac eleifend elit feugiat. Duis vehicula purus in tellus vestibulum, eget suscipit nibh convallis. Pellentesque orci elit, ultrices in pellentesque a, convallis quis enim. Aenean at porta lacus. Donec sollicitudin viverra lacus et ultrices. Suspendisse malesuada ligula eu leo dictum, non viverra metus varius. Mauris sit amet placerat neque. Cras consequat tortor et quam lacinia, vel gravida dui consectetur. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Fusce eu nisi sapien.\n"
  ]
