var texts = [
  "My art lineage is almost non-existent. Both of my parents work simple, blue-color jobs, and neither has any particular interest in any art forms. They hardly even watch movies. My taste in art has grown organically, almost entirely out of my love for computers. The digital, deterministic-ness of technology has always pacified me, and it is a limitlessly expressful medium.",
  "I find nothing more relaxing than sitting down at my computer and making a website or expressing myself with code. Being able to bring an idea to life is incredibly gratifying.",
  "When I was 15, I wanted to build something. I had an idea for an electrical door lock, and it could only be opened by a pattern swiped through a laser beam. I had no idea what I was doing. I'd only torn things apart before, I had never put something together. So I bought all the pieces and wrote the programs and drilled and glued and stapled until I had what I wanted.",
  "That moment between nonexistence and creation occured at the literal speed of light. I flipped the switch, and watched as all of the parts I had cobbled together came to life. Lasers lit up and recognized patterns, motors whirred, and the project was completed. The surprising thing I learned about myself was that I could bring things to life.",
  "My own unabashed art work of change would be a sculpture of all of the storage media humanity has created since we first made persistent storage in the 50s. I’d start with vacuum tubes and huge platters that used to cost millions of dollars and would only hold mere kilobytes, millionths of what we can fit on a card the size of a thumbnail today.",
  "No other technology in the history of mankind has become so much faster, so much smaller, and so much more information dense. The scale is enormous, a change of nine orders of magnitude across the board. Even our speed of communication, which used to be horses and now is the speed of light, doesn’t compare to the advances we’ve made in storage technology. So, my sculpture would show the old vacuum tubes and huge platters as an evolution, decreasing in size and increasing in performance, smaller and smaller, until we eventually reached modern technology, barely the size of a fingernail.",
  "In the most literal sense, sound is a delta in air pressure that causes oscillations in tiny hairs on the inside of our ears, which our brains interpret as sound. Though less literally, there is a definitive difference between “sound”, and “noise”. Noise is just that definition above, there’s no order to it, no rhyme or reason. Sound, however, is when noise has meaning to us. Another human being’s voice, a dog barking, the sound of rain on a cloudy day, these have significance to us and transcend the boundary between noise and sound by being more than just a passive air pressure difference.",
  "Both complexity and simplicity have their place in good art, though deriving meaning from a “simple” work can often be more rewarding and gratifying. For example, Clapping Music is an incredibly simple piece, consisting of one beat played over and over again. Despite this, it sounds dynamic and complex, and I think you can derive an immensity of meaning from what that actually says. More complex works, like something from Stravinsky or Mozart, can push you around emotionally and take you on a journey, which just isn’t possible from a monochromatic piece."
];
